### PR TITLE
Review on my project so far

### PR DESCRIPTION
**Pull request by karlsc**
Hello,

I am at the point where I need to find hwo to configure the edit thing.

If you have time to look at what i did and give me some feedbacks, it would be greatly appreciated!

### CODE REVIEW

**Comment by nyanofthemoon** [comment]
When I run the code, if I either search for or try and enter a new entry, after that piece of code is executed, the program ends. Should it return to the main menu?

**Comment by karlysun** [comment]
My code as changed a lot since, I think I pushed a version that wasn't properly working.

**Comment by nyanofthemoon** [comment]
Getting there! When I edit an existing entry, the program ends.

**Comment by karlysun** [comment]
Thoese things work now and birthdate can be whatever if I remember the instructions properly.

**Pull request closed without merging**
